### ISSUE TITLE
SharingAssetCollection V2 doesn't work with MRTK v2.1

### ISSUE THREAD

**Issue by AMollis** [MicrosoftDocs/mixed-reality#1691]
If you happen to download the latest MRTK v2.1, the [SharingAssetCollection V2](https://github.com/microsoft/MixedRealityLearning/releases/tag/development) will not work.  You'll get the following errors:

```
Assets\BaseModuleAssets\Base Module Scripts\MoveWithPan.cs(6,43): error CS0246: The type or namespace name 'IMixedRealityHandPanHandler' could not be found (are you missing a using directive or an assembly reference?)
Assets\BaseModuleAssets\Base Module Scripts\MoveWithPan.cs(20,28): error CS0246: The type or namespace name 'HandPanEventData' could not be found (are you missing a using directive or an assembly reference?)
Assets\BaseModuleAssets\Base Module Scripts\MoveWithPan.cs(25,27): error CS0246: The type or namespace name 'HandPanEventData' could not be found (are you missing a using directive or an assembly reference?)
Assets\BaseModuleAssets\Base Module Scripts\MoveWithPan.cs(33,30): error CS0246: The type or namespace name 'HandPanEventData' could not be found (are you missing a using directive or an assembly reference?)

```

The samples should be updated to the latest MRTK, or the documentation should be explicit that it only works with a particular version of the MRTK.
