### ISSUE TITLE
SharingAssetCollection package out of date

### ISSUE THREAD

**Issue by njwilsonISU** [MicrosoftDocs/mixed-reality#1658]
The sharing package linked on this page is out of date and does not work with MRTK 2.0.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c749260f-d284-74f9-ffff-9afd2069ef81
* Version Independent ID: 04aff1f3-9c67-07f5-4fe2-6b1fd256e9f3
* Content: [Multi-user capabilities tutorials - 2. Getting Unity ready for development - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch2#feedback)
* Content Source: [mixed-reality-docs/mrlearning-sharing(photon)-ch2.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/mrlearning-sharing(photon)-ch2.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by njwilsonISU** [comment]
First error
> Assets\BaseModuleAssets\Base Module Scripts\MoveWithPan.cs(6,43): error CS0246: The type or namespace name 'IMixedRealityHandPanHandler' could not be found (are you missing a using directive or an assembly reference?)

Second error
> Assets\BaseModuleAssets\Base Module Scripts\MoveWithPan.cs(20,28): error CS0246: The type or namespace name 'HandPanEventData' could not be found (are you missing a using directive or an assembly reference?)

After dealing with these, a couple more come up. The scripts in the package need updating.
